spring.application.name=bussinestask
server.port=${PORT:8001}
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:usuarios}
spring.datasource.url=jdbc:mysql://localhost:3306/bussines_task?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
logging.file.path=/app/logs

#EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Las credenciales del correo seran subidas a la plataforma SENA mientras revisan la tarea, luego seran eliminadas
spring.mail.username=scardona0297@gmail.com
spring.mail.password=oyvl gcjw zslk icet

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
